experiment:
    name: run1
    project_name: MUSE
    output_folder: outputs/muse
    max_train_examples: 1000000
    save_every: 1000
    eval_every: 500
    sample_every: 1000
    log_every: 100
    log_level: info
    resume_path_from_checkpoint: outputs/muse/checkpoints/MUSE.pt


codebook:
        codebook_dim: 32
        beta : 0.25
        codebook_size: 8192

vitvqgan:
    checkpoint : outputs/vitvqgan/checkpoints/VitVQGAN.pt
    transformer:
        dim : 768
        patch_size : 8
        n_heads : 12
        d_head : 64
        depth : 12
        dropout : 0.1
        mlp_dim: 3072

model:
    name: muse
    dim : 512
    encoder:
        type: clip
        name : openai/clip-vit-base-patch32
        max_length : 77
    decoder:
        patch_size : 8
        n_heads : 8
        d_head : 64
        depth : 6

dataset:
    name: coco
    params:
        train_path:  /media/pranoy/UBUNTU_ROOT/home/pranoy/datasets/coco2017
        val_path: null
        num_workers: 4
        pin_memory: True
        batch_size: 8
        persistent_workers: True
        shuffle : True
        train_test_split : 0.9
    preprocessing:
        resolution: 256
        center_crop: False
        random_flip: False
        random_crop: False
        mean : [0.5, 0.5, 0.5]
        std : [0.5, 0.5, 0.5]

optimizer:
    name: adamw
    params: 
        learning_rate: 0.0001
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.0
        epsilon: 1e-8

lr_scheduler:
    scheduler: cosine_with_warmup
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 4000

training:
    gradient_accumulation_steps: 16
    mixed_precision: "no"
    seed: 42
    num_epochs: 200
    max_grad_norm: 1.0
