experiment:
    name: run1
    project_name: vit_moe
    output_folder: outputs/vit_moe
    max_train_examples: 1000000
    save_every: 1000
    eval_every: 500
    sample_every: 1000
    log_every: 100
    log_level: info
    resume_path_from_checkpoint: null

model:
    name: vit_moe
    dim : 512
    transformer:
        dim : 512
        patch_size : 16
        n_heads : 8
        d_head : 64
        depth : 6
        dropout : 0.1
        n_experts: 5
        sel_experts: 2
        num_classes : 1000

dataset:
    name: imagenet
    params:
        train_path:  /home/pranoy/Downloads/imagenet
        val_path: null
        num_workers: 4
        pin_memory: True
        batch_size: 32
        persistent_workers: True
        shuffle : True
        train_test_split : 0.9
    preprocessing:
        resolution: 512
        center_crop: False
        random_flip: False
        random_crop: False
        mean : [0.485, 0.456, 0.406]
        std : [0.229, 0.224, 0.225]

optimizer:
    name: adamw
    params: 
        learning_rate: 1e-3
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.05
        epsilon: 1e-8

lr_scheduler:
    scheduler: cosine_with_warmup
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 100

training:
    gradient_accumulation_steps: 32
    mixed_precision: "no"
    seed: 42
    num_epochs: 200
