experiment:
    name: run1
    project_name: VQGAN
    output_folder: outputs/VQGAN
    max_train_examples: 1000000
    save_every: 1000
    eval_every: 500
    sample_every: 1000
    log_every: 100
    log_level: info
    resume_path_from_checkpoint: null


codebook:
        codebook_dim: 256
        beta : 0.25
        codebook_size: 8192

model:
    name: vqgan


dataset:
    name: coco
    params:
        train_path:  /media/pranoy/UBUNTU_ROOT/home/pranoy/datasets/coco2017
        val_path: null
        num_workers: 4
        pin_memory: True
        batch_size: 8
        persistent_workers: True
        shuffle : True
        train_test_split : 0.9
    preprocessing:
        resolution: 256
        center_crop: False
        random_flip: True
        random_crop: True
        mean : [0.5, 0.5, 0.5]
        std : [0.5, 0.5, 0.5]
        scale : 0.66

optimizer:
    name: adamw
    params: 
        learning_rate: 0.0001
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.0001
        epsilon: 1e-8

lr_scheduler:
    scheduler: cosine_with_warmup
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 50000
        decay_steps: 100000

training:
    gradient_accumulation_steps: 16
    mixed_precision: "no"
    seed: 42
    num_epochs: 200
    max_grad_norm: null
